/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./*.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#003b0f",
        "outline": "#727782",
        "tertiary-container": "#57ac5d",
        "inverse-on-surface": "#f0f1f2",
        "surface-container-low": "#f3f4f5",
        "surface-container-high": "#e7e8e9",
        "on-tertiary-fixed-variant": "#005318",
        "on-secondary": "#ffffff",
        "primary-fixed": "#d4e3ff",
        "secondary-fixed": "#ffd9df",
        "on-tertiary-fixed": "#002105",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#83da85",
        "on-primary-fixed-variant": "#004884",
        "primary": "#075fab",
        "background": "#f8f9fa",
        "primary-container": "#5d9cec",
        "on-secondary-container": "#590025",
        "on-secondary-fixed-variant": "#8f003f",
        "surface-container": "#edeeef",
        "tertiary": "#126d27",
        "tertiary-fixed": "#9ff79f",
        "secondary-fixed-dim": "#ffb1c2",
        "surface-container-highest": "#e1e3e4",
        "surface-dim": "#d9dadb",
        "error": "#ba1a1a",
        "inverse-primary": "#a4c9ff",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#a4c9ff",
        "on-primary-container": "#003260",
        "secondary": "#b80f55",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#001c39",
        "surface-variant": "#e1e3e4",
        "outline-variant": "#c1c6d3",
        "error-container": "#ffdad6",
        "surface-tint": "#075fab",
        "on-surface": "#191c1d",
        "surface": "#f8f9fa",
        "secondary-container": "#fd4e87",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2e3132",
        "on-secondary-fixed": "#3f0018",
        "surface-bright": "#f8f9fa",
        "on-surface-variant": "#414751",
        "on-background": "#191c1d"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
